version: '3.8'

services:
  lidar_postgres_1:
    # Database to store all vector data, states, and links to raster data.
    image: postgis/postgis
    container_name: cont_lidar_postgres_1
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: pg_isready -h 127.0.0.1 -U $POSTGRES_USER -d $POSTGRES_DB

  lidar_run_1:
    # Performs analysis, computation, handles web requests, facilitates database interactions
    image: lidar_run_1
    container_name: cont_lidar_run_1
    build:
      context: docker
      args:
        - WITH_SUDO=yes
    env_file:
      - .env
    ports:
      - "8786:8787"
      - "8887:8888"
    volumes:
      - "./workspace:/home/jovyan"
      - "../datastorage:/home/jovyan/datastorage"
    depends_on:
      lidar_postgres:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"
