# YML file for setting up Python environment
name: lidar
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - python-dotenv
  - pytest
  - lxml
  - pandas
  - geopandas
  - geojson
  - python-pdal
  - pdal
  - gdal
  - pygeos
  - shapely
  - psycopg2
  - sqlalchemy<2.0  # v2.0 does not supported by some packages yet.
  - geoalchemy2
  - scrapy
  - dask
  - bokeh!=3.0.*,>=2.4.2  # for Dask dashboard
  - pip:
    - laspy[lazrs,laszip]  # for vertical datum transference
    - geofabrics==1.1.2
prefix:
